### PR TITLE
Fix  unbound variable

### LINKED ISSUE #1358: HUSKY: unbound variable
```shell
.husky/_/h: line 13: HUSKY: unbound variable
```

**Context**

~/.config/husky/init.sh 
```shell
#!/usr/bin/env sh
set -eu

[ -e /etc/zshenv ] && . /etc/zshenv
[ -e "${ZDOTDIR:=${HOME}}/.zshenv" ] && . "${ZDOTDIR:=${HOME}}/.zshenv"
[ -e /etc/zprofile ] && . /etc/zprofile
[ -e "${ZDOTDIR:=${HOME}}/.zprofile" ] && . "${ZDOTDIR:=${HOME}}/.zprofile"
[ -e /etc/zlogin ] && . /etc/zlogin
[ -e "${ZDOTDIR:=${HOME}}/.zlogin" ] && . "${ZDOTDIR:=${HOME}}/.zlogin"
```

**Possible Solution**

Use

`${HUSKY:-}`

instead of

`$HUSKY`

in the `h` script.

**Background Info**

https://stackoverflow.com/a/44606194

### PR DESCRIPTION
**Pull request by typicode**
Fixes #1358

### CODE REVIEW

File: husky.sh [hunk 1]
```diff
@@ -1,5 +1,6 @@
 #!/usr/bin/env sh
-[ "$HUSKY" = "2" ] && set -x
+H="$HUSKY"
```
Comment (glensc) [inline husky.sh:2]: this doesn't fix anything, you still have unbound `$HUSKY` access. what you should had done is `H="${HUSKY:-}"` which was actually described in https://github.com/typicode/husky/issues/1358 issue body.

Comment (glensc) [reply husky.sh:2]: feedback is in the pr itself:
- https://github.com/typicode/husky/issues/1358#issuecomment-1914651245
